### ISSUE TITLE
一些优化点

### ISSUE THREAD

**Issue by gbk** [tinglejs/generator-tingle#8]
- 开发工具和脚手架分离，允许用户单独更新开发工具。
  https://github.com/tinglejs/tingle-dev-tools
- 增加项目目录结构和配置的更新任务，以适应脚手架的变化。
  yo tingle:upgrade

**Comment by gbk** [comment]
初步测试了一下，有待进一步测试。

TODO: upgrade 任务要增加文件头写入。

**Comment by jias** [comment]
给力

**Comment by gbk** [comment]
已增加文件头版权信息的写入。

文档待完善。
